name: Go Tests
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: true

      - name: Install X11 dependencies
        run: sudo apt-get update && sudo apt-get install -y libx11-dev xorg-dev

      - name: Install dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Run vet
        run: go vet ./...

      - name: Make test repo
        run: go run scripts/mkrepo.go

      - name: Run tests
        run: go test -v -race -timeout 30s ./...
